USE monster;

DELETE FROM `monsters`;

INSERT INTO `monsters` (`id_monsters`, `nom`, `description`, `image`) VALUES
(NULL, 'gnarly_beast', '', '/assets/beast/gnarly_beast.avif'),
(NULL, 'killer_beast', '', '/assets/beast/killer_beast.avif'),
(NULL, 'mean_beast', '', '/assets/beast/mean_beast.avif'),
(NULL, 'peach_beast', '', '/assets/beast/peach_beast.avif'),
(NULL, 'pink_beast', '', '/assets/beast/pink_beast.avif'),
(NULL, 'scary_beast', '', '/assets/beast/scary_beast.avif'),
(NULL, 'white_beast', '', '/assets/beast/white_beast.avif'),

(NULL, 'caramel_java', '', '/assets/java/caramel_java.webp'),
(NULL, 'irish_java', '', '/assets/java/irish_java.webp'),
(NULL, 'latte_java', '', '/assets/java/latte_java.webp'),
(NULL, 'locamoca_java', '', '/assets/java/locamoca_java.webp'),
(NULL, 'mean_java', '', '/assets/java/mean_java.webp'),

(NULL, 'badapple_juice', '', '/assets/juice/badapple_juice.webp'),
(NULL, 'khaotic_juice', '', '/assets/juice/khaotic_juice.webp'),
(NULL, 'limonade_juice', '', '/assets/juice/limonade_juice.webp'),
(NULL, 'mango_juice', '', '/assets/juice/mango_juice.webp'),
(NULL, 'mixxd_juice', '', '/assets/juice/mixxd_juice.webp'),
(NULL, 'monarch_juice', '', '/assets/juice/monarch_juice.webp'),
(NULL, 'pacific_juice', '', '/assets/juice/pacific_juice.webp'),
(NULL, 'pipeline_juice', '', '/assets/juice/pipeline_juice.webp'),
(NULL, 'rio_juice', '', '/assets/juice/rio_juice.webp'),
(NULL, 'ripper_juice', '', '/assets/juice/ripper_juice.webp'),
(NULL, 'viking_juice', '', '/assets/juice/viking_juice.webp'),
(NULL, 'voodoo_juice', '', '/assets/juice/voodoo_juice.webp'),

(NULL, 'cosmic_nitro', '', '/assets/nitro/cosmic_nitro.webp'),
(NULL, 'superdry_nitro', '', '/assets/nitro/superdry_nitro.webp'),

(NULL, 'assault_original', '', '/assets/origine/assault_original.webp'),
(NULL, 'elecblue_original', '', '/assets/origine/elecblue_original.webp'),
(NULL, 'lando_original', '', '/assets/origine/lando_original.webp'),
(NULL, 'locarb_original', '', '/assets/origine/locarb_original.webp'),
(NULL, 'og_original', '', '/assets/origine/og_original.webp'),
(NULL, 'orangedreamsicle_original', '', '/assets/origine/orangedreamsicle_original.webp'),
(NULL, 'strawberry_original', '', '/assets/origine/strawberry_original.webp'),
(NULL, 'superpremium_original', '', '/assets/origine/superpremium_original.webp'),
(NULL, 'zs_full_original', '', '/assets/origine/zs_full_original.webp'),
(NULL, 'zs_og_original', '', '/assets/origine/zs_og_original.webp'),
(NULL, 'zs_original', '', '/assets/origine/zs_original.webp'),
(NULL, 'zs_strawberry_original', '', '/assets/origine/zs_strawberry_original.webp'),

(NULL, 'green_rehab', '', '/assets/rehab/green_rehab.webp'),
(NULL, 'lemonade_rehab', '', '/assets/rehab/lemonade_rehab.webp'),
(NULL, 'peach_rehab', '', '/assets/rehab/peach_rehab.webp'),
(NULL, 'wild_rehab', '', '/assets/rehab/wild_rehab.webp'),

(NULL, 'orangedreamsicle_reserve', '', '/assets/reserve/orangedreamsicle_reserve.webp'),
(NULL, 'peaches_reserve', '', '/assets/reserve/peaches_reserve.webp'),
(NULL, 'pi', '', '/assets/reserve/pi.webp'),
(NULL, 'watermelon_reserve', '', '/assets/reserve/watermelon_reserve.webp'),

(NULL, '172d2ac5-a1fd-40f4-a477-5d045d62982e', '', '/assets/ultra/172d2ac5-a1fd-40f4-a477-5d045d62982e.webp'),
(NULL, 'blue_ultra', '', '/assets/ultra/blue_ultra.webp'),
(NULL, 'fantasy_ultra', '', '/assets/ultra/fantasy_ultra.webp'),
(NULL, 'fiesta_ultra', '', '/assets/ultra/fiesta_ultra.webp'),
(NULL, 'golden_ultra', '', '/assets/ultra/golden_ultra.webp'),
(NULL, 'hawaii_ultra', '', '/assets/ultra/hawaii_ultra.webp'),
(NULL, 'paradise_ultra', '', '/assets/ultra/paradise_ultra.webp'),
(NULL, 'peachy_ultra', '', '/assets/ultra/peachy_ultra.webp'),
(NULL, 'punk_ultra', '', '/assets/ultra/punk_ultra.webp'),
(NULL, 'red_ultra', '', '/assets/ultra/red_ultra.webp'),
(NULL, 'rosa_ultra', '', '/assets/ultra/rosa_ultra.webp'),
(NULL, 'rwb_ultra', '', '/assets/ultra/rwb_ultra.webp'),
(NULL, 'strawberry_ultra', '', '/assets/ultra/strawberry_ultra.webp'),
(NULL, 'sunrise_ultra', '', '/assets/ultra/sunrise_ultra.webp'),
(NULL, 'viceguava_ultra', '', '/assets/ultra/viceguava_ultra.webp'),
(NULL, 'violet_ultra', '', '/assets/ultra/violet_ultra.webp'),
(NULL, 'watermelon_ultra', '', '/assets/ultra/watermelon_ultra.webp'),
(NULL, 'white_ultra', '', '/assets/ultra/white_ultra.webp'),
(NULL, 'wild_ultra', '', '/assets/ultra/wild_ultra.webp');